### ISSUE TITLE
Please add offline installation tutorial

### ISSUE THREAD

**Issue by 01joy** [bfontaine/term2048#33]
Hi bfontaine,

`term2048` is an amazing app, I like it.

But someone may want to install it offline instead of pip installing.

I have figured out `term2048` can be installed offline by following steps:

1. download `term2048` repo
2. make deps
3. make check
4. sudo python setup.py install

Many beginners don't know the fourth step as it's not mentioned in current readme. It will be of great help to many people if you add the fourth step in your readme.

Thank you.

**Comment by bfontaine** [comment]
Hi @01joy, what do you mean by “offline”? You still have to download the repo and `make deps` *will* use `pip` to install dependencies.

**Comment by 01joy** [comment]
Hi @bfontaine , but someone may don't know they have to `sudo python setup.py install`.

**Comment by bfontaine** [comment]
I added it in a dedicated section: https://github.com/bfontaine/term2048#install-from-source

**Comment by 01joy** [comment]
It's very nice of you to add `install from source`, thank you.
